baseURL = "https://deine-domain.com/"
languageCode = "de-de"
title = "Meine persönliche Website"
theme = "paige"

[params]
  author = "Dein Name"
  description = "Meine persönliche Website mit Blog"
  dateFormat = "02.01.2006"


[[menu.main]]
  name = "Über mich"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
